In [1]:
import numpy as np
print(np.__version__)

2.2.3


In [4]:
list = [10, 20, 30, 40, 50]
arr = np.array(list)
print(arr)
print('Type:', type(arr))
print('Shape',arr.shape)

[10 20 30 40 50]
Type: <class 'numpy.ndarray'>
Shape (5,)


In [5]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape) #rows  and columns
print(arr1.size) #length
print(arr1[0]) #first row
print(arr1[0][2]) #first row 2nd column

[[1 2 3]
 [4 5 6]]
(2, 3)
6
[1 2 3]
3


In [6]:
#Generate array
arr1=np.zeros([2,3])
print(arr1)
print(arr1[0][1])

[[0. 0. 0.]
 [0. 0. 0.]]
0.0


In [7]:
arr2=np.ones([3,3])
print(arr2)
print(arr1[0][1])

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0.0


In [13]:
arr3=np.arange(1,10,3) #[1,4,7]
arr4=np.arange(2,10,3) #[2,5,8]
print(arr3+arr4) #[3,9,15]
print(arr3*arr4) #multiply
print(arr3**2)

[ 3  9 15]
[ 2 20 56]
[ 1 16 49]


In [12]:
sample=np.array([np.arange(1,10,3),np.arange(2,10,3)])
print(sample)

[[1 4 7]
 [2 5 8]]


In [15]:
purchases = np.array([
    [200, 150, 100],
    [300, 250, 400],
    [100, 200, 300],
    [500, 600, 700],
    [50, 60, 70]
])
 
total_spend = purchases.sum(axis = 1)
 
average_spend = purchases.mean(axis = 1)
 
print("Total spend:", total_spend)
print("Average spend:", average_spend)
print(max(average_spend))


Total spend: [ 450  950  600 1800  180]
Average spend: [150.         316.66666667 200.         600.          60.        ]
600.0


In [18]:
A=np.array([[2,3],[4,1]])

B=np.array([8,10])

solution=np.linalg.solve(A,B) #Linear Algorithm
print(solution)

[2.2 1.2]


In [20]:
sales=np.array([1000,2000,1800,1500,1900,2000,1750,6476,8484,2344])
total_sales=sum(sales)
print(total_sales)

29254


In [21]:
avg_sales=np.mean(sales)
print(avg_sales)

2925.4


In [22]:
print(max(sales))

8484


In [23]:
print(min(sales))

1000


In [27]:
days_above_average = np.sum(sales > avg_sales)
 
print(f"Average Sales: {avg_sales}")
print(f"Number of days with sales above average: {days_above_average}")
 
for num in sales:
    increase = 1.1 * num
 
    print(increase)
 

Average Sales: 2925.4
Number of days with sales above average: 2
1100.0
2200.0
1980.0000000000002
1650.0000000000002
2090.0
2200.0
1925.0000000000002
7123.6
9332.400000000001
2578.4


In [28]:
sales.sort()
print(sales)

[1000 1500 1750 1800 1900 2000 2000 2344 6476 8484]


In [30]:
import pandas as pd
df=pd.read_csv("sales_data.csv")

In [31]:
df


Order_ID       Product     Category  Quantity  Price  Total_Amount  \
0      1001        Laptop  Electronics         2    700           NaN   
1      1002  Mobile Phone  Electronics         1    500           NaN   
2      1003    Headphones  Accessories         3     50           NaN   
3      1004         Mouse  Accessories         2     20           NaN   
4      1005      Keyboard  Accessories         1     30           NaN   
5      1006       T-shirt     Clothing         4     15           NaN   
6      1007        Jacket     Clothing         1     60           NaN   
7      1008  Refrigerator  Electronics         1    900           NaN   
8      1009            TV  Electronics         2   1100           NaN   
9      1010         Shoes     Clothing         2     40           NaN   

         Date  
0  2024-02-01  
1  2024-02-02  
2  2024-02-03  
3  2024-02-04  
4  2024-02-05  
5  2024-02-06  
6  2024-02-07  
7  2024-02-08  
8  2024-02-09  
9  2024-02-10

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Order_ID      10 non-null     int64  
 1   Product       10 non-null     object 
 2   Category      10 non-null     object 
 3   Quantity      10 non-null     int64  
 4   Price         10 non-null     int64  
 5   Total_Amount  0 non-null      float64
 6   Date          10 non-null     object 
dtypes: float64(1), int64(3), object(3)
memory usage: 692.0+ bytes


In [33]:
df.isnull()

Order_ID  Product  Category  Quantity  Price  Total_Amount   Date
0     False    False     False     False  False          True  False
1     False    False     False     False  False          True  False
2     False    False     False     False  False          True  False
3     False    False     False     False  False          True  False
4     False    False     False     False  False          True  False
5     False    False     False     False  False          True  False
6     False    False     False     False  False          True  False
7     False    False     False     False  False          True  False
8     False    False     False     False  False          True  False
9     False    False     False     False  False          True  False

In [34]:
df.isna()

Order_ID  Product  Category  Quantity  Price  Total_Amount   Date
0     False    False     False     False  False          True  False
1     False    False     False     False  False          True  False
2     False    False     False     False  False          True  False
3     False    False     False     False  False          True  False
4     False    False     False     False  False          True  False
5     False    False     False     False  False          True  False
6     False    False     False     False  False          True  False
7     False    False     False     False  False          True  False
8     False    False     False     False  False          True  False
9     False    False     False     False  False          True  False

In [36]:
df.fillna(0) ##handling missing values

Order_ID       Product     Category  Quantity  Price  Total_Amount  \
0      1001        Laptop  Electronics         2    700           0.0   
1      1002  Mobile Phone  Electronics         1    500           0.0   
2      1003    Headphones  Accessories         3     50           0.0   
3      1004         Mouse  Accessories         2     20           0.0   
4      1005      Keyboard  Accessories         1     30           0.0   
5      1006       T-shirt     Clothing         4     15           0.0   
6      1007        Jacket     Clothing         1     60           0.0   
7      1008  Refrigerator  Electronics         1    900           0.0   
8      1009            TV  Electronics         2   1100           0.0   
9      1010         Shoes     Clothing         2     40           0.0   

         Date  
0  2024-02-01  
1  2024-02-02  
2  2024-02-03  
3  2024-02-04  
4  2024-02-05  
5  2024-02-06  
6  2024-02-07  
7  2024-02-08  
8  2024-02-09  
9  2024-02-10

In [37]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [38]:
df.dtypes

Order_ID          int64
Product          object
Category         object
Quantity          int64
Price             int64
Total_Amount    float64
Date             object
dtype: object

In [40]:
df['Date']=pd.to_datetime(df['Date'])

In [41]:
df.dtypes

Order_ID                 int64
Product                 object
Category                object
Quantity                 int64
Price                    int64
Total_Amount           float64
Date            datetime64[ns]
dtype: object

In [42]:
df['Product']=df['Product'].astype(str)
df.dtypes

Order_ID                 int64
Product                 object
Category                object
Quantity                 int64
Price                    int64
Total_Amount           float64
Date            datetime64[ns]
dtype: object

In [43]:
data=np.array([10,12,14,15,18,21,25,100])
Q1=np.percentile(data,25)
Q3=np.percentile(data,75)
IQR=Q3-Q1
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR

outliers=data[(data<lower_bound) | (data>upper_bound)]
print(outliers)

[100]


In [ ]:
import matplot